### PR TITLE
Fix #400, keep precision in case of big numbers

### LINKED ISSUE #400: maximum field does not work properly with numbers around 1.0E16
schema:
`
{   
    "type": "number",
    "maximum": 9999999999999999    
}
`
payload:
`10000000000000000` or `10000000000000001`
This does not return a maximum value exceeded validation. 

**Note:** When the payload is `10000000000000002` the validation is returned correctly.

**Observations**
From debugging the code i found that when calling .doubleValue() in https://github.com/everit-org/json-schema/blob/master/core/src/main/java/org/everit/json/schema/NumberSchemaValidatingVisitor.java#L67 the number is truncated to 1.0E16 as well as the numberSubject value.

### PR DESCRIPTION
**Pull request by zgyorffi**

### CODE REVIEW

File: core/src/main/java/org/everit/json/schema/NumberSchemaValidatingVisitor.java [hunk 1]
```diff
@@ -41,17 +42,17 @@ void visitMinimum(Number minimum) {
         if (minimum == null) {
             return;
         }
-        if (exclusiveMinimum && numberSubject <= minimum.doubleValue()) {
+        if (exclusiveMinimum && compare(numberSubject, minimum) <= 0) {
             owner.failure(subject + " is not greater than " + minimum, "exclusiveMinimum");
-        } else if (numberSubject < minimum.doubleValue()) {
+        } else if (compare(numberSubject, minimum) < 0) {
```
Comment (erosb) [inline core/src/main/java/org/everit/json/schema/NumberSchemaValidatingVisitor.java:47]: Can you please extract the `compare(numberSubject, minimum)` value into a local variable?

File: core/src/main/java/org/everit/json/schema/NumberSchemaValidatingVisitor.java [hunk 2]
```diff
@@ -62,9 +63,9 @@ void visitMaximum(Number maximum) {
         if (maximum == null) {
             return;
         }
-        if (exclusiveMaximum && maximum.doubleValue() <= numberSubject) {
+        if (exclusiveMaximum && compare(maximum, numberSubject) <= 0) {
             owner.failure(subject + " is not less than " + maximum, "exclusiveMaximum");
-        } else if (maximum.doubleValue() < numberSubject) {
+        } else if (compare(maximum, numberSubject) < 0) {
```
Comment (erosb) [inline core/src/main/java/org/everit/json/schema/NumberSchemaValidatingVisitor.java:68]: Can you please extract the `compare(maximum, numberSubject)` value into a local variable?

**Review by erosb — CHANGES_REQUESTED** [review]
Thank you for the thorough test coverage @zgyorffi ! I added two minor comments.
